name: arm-field-site-cookbook-dev
channels:
  - conda-forge
dependencies:
  - python=3.11
  - mystmd
  - cookiecutter
  - act-atmos
  - jupyterlab
  - arm_pyart
  - cartopy
  - matplotlib
  - pydda
  - jaxopt
  - tensorflow>=2.6
  - xradar
  - tensorflow-probability>=0.24
  - xwrf
  - tobac
  - plotly
